--관리자접속

CREATE TABLESPACE RENTBOOKDB
DATAFILE 'C:/oraclexe/data/rentbook.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER userbook IDENTIFIED BY userbook
DEFAULT TABLESPACE RENTBOOKDB;

GRANT DBA TO userbook;