--관리자접속

CREATE TABLESPACE RENTBOOKDB
DATAFILE 'C:/oraclexe/data/rentbook.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

CREATE USER bookuser IDENTIFIED BY bookuser
DEFAULT TABLESPACE RENTBOOKDB;

GRANT DBA TO bookuser;

DROP USER userbook CASCADE;